# Generated by Django 5.0.6 on 2025-03-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='comment_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='like_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='upload_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webseries',
            name='comment_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webseries',
            name='like_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webseries',
            name='trailer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='webseries',
            name='upload_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
